ads/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^coupons/', views.coupons, name='coupons'),
    url(r'^about/', views.about_us, name='about'),
    url(r'^categories/', views.categories, name='categories'),
    url(r'^search/', views.search, name='search'),
    url(r'^get_categories/', views.get_categories, name='get_categories'),
    url(r'get_states/', views.get_states, name='get_states'),
    url(r'^ads/', views.ads, name='ads'),
    url(r'ad_detail/(?P<pk>[\d]+)$', views.ad_detail, name='ad_detail'),
    url(r'ads_by_category/(?P<pk>[\d]+)$', views.CategoriesListView.as_view(), name='ads_by_category'),
    url(r'^api_ads/$', views.ad_list, name='api_ads'),
    url(r'^api_search_ad/$', views.search_ad, name='api_search_ad'),
    url(r'^api_coupon/$', views.get_coupon, name='api_coupon'),
    url(r'^api_get_info/$', views.get_info, name='api_get_info'),
    url(r'^api_get_categories/$', views.get_categories_api, name='api_get_categories'),
    url(r'^api_most_recent/$', views.get_most_recent, name='api_most_recent'),
    url(r'^api_mobile_banner/$', views.get_mobile_banner, name='api_mobile_banner')

]
urlpatterns = format_suffix_patterns(urlpatterns)

guia_libre/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ads.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os

from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.dispatch import receiver
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from geoposition.fields import GeopositionField

# region Constants
DURATION = 'Duración'
BASE_MODEL_CREATED = 'Creado'
BASE_MODEL_MODIFIED = 'Modificado'
BASE_MODE_CREATED_BY = 'Creado por'
BASE_MODE_MODIFIE_BY = 'Modificado por'
NAME = 'Nombre(s)'
LAST_NAME = 'Apellido(s)'
PHONE = 'Teléfono'
CELL = 'Celular'
TITLE = 'Título'
DESC = 'Descripción'
ADVERTISER = 'Anunciante'
ADVERTISERS = 'Anunciantes'
AD = 'Anuncio'
AD_LOCATION = 'Ubicación'
ADS = 'Anuncios'
AD_STATE = 'Estado'
IMAGE = 'Imagen'
IMAGES = 'Imágenes'
EMAIL = 'Correo electrónico'
TRADE_NAME = 'Nombre comercial'
COUPON = 'Cupón'
COUPONS = 'Cupones'
COUPON_NAME = 'Nombre'
COUPON_DATE = 'Fecha'
COUPON_ACTIVE = 'Activo'
CONTACT = 'Contacto'
CONTACTS = 'Contactos'
ABOUT = '¿Quiénes somos?'
MISSION = 'Misión'
VISION = 'Visión'
VALUES = 'Valores'
CONTACT_ADDRESS = 'Dirección'
CONTACT_COUNTRY = 'País'
CONTACT_PHONE = 'Teléfono'
CONTACT_EMAIL = 'Correo electrónico'
CATEGORY_NAME = 'Categoria'
CATEGORY_ICON = 'Icono'
SUBCATEGORY = 'Subcategoría'
SUBCATEGORIES = 'Subcategorías'
SUBCATEGORY_NAME = 'Nombre'
CATEGORY = 'Categoría'
CATEGORIES = 'Categorías'
BANNER = 'Banner'
BANNERS = 'Banners'
BANNERS_GROUP = 'Grupo de banners'
BANNERS_GROUPS = 'Grupos de banners'
BANNER_GROUP_NAME = 'Nombre'
BANNER_GROUP_ACTIVE = 'Activo'

MOBILE_BANNER = 'Banner para móvil'
MOBILES_BANNERS = 'Banners para móviles'
MOBILE_BANNERS_GROUP = 'Grupo de banners para móviles'
MOBILES_BANNERS_GROUPS = 'Grupos de banners para móviles'
MOBILE_BANNER_GROUP_NAME = 'Nombre'
MOBILE_BANNER_GROUP_ACTIVE = 'Activo'
# endregion

# region State choices
STATES = (
    ('Aguascalientes', 'Aguascalientes'),
    ('Baja California', 'Baja California'),
    ('Baja California Sur', 'Baja California Sur'),
    ('Campeche', 'Campeche'),
    ('Chihuahua', 'Chihuahua'),
    ('Chiapas', 'Chiapas'),
    ('Coahuila', 'Coahuila'),
    ('Colima', 'Colima'),
    ('Ciudad de México', 'Ciudad de México'),
    ('Durango', 'Durango'),
    ('Guerrero', 'Guerrero'),
    ('Guanajuato', 'Guanajuato'),
    ('Hidalgo', 'Hidalgo'),
    ('Jalisco', 'Jalisco'),
    ('Michoacán', 'Michoacán'),
    ('Morelos', 'Morelos'),
    ('Nayarit', 'Nayarit'),
    ('Nuevo León', 'Nuevo León'),
    ('Oaxaca', 'Oaxaca'),
    ('Puebla', 'Puebla'),
    ('Querétaro', 'Querétaro'),
    ('Quintana Roo', 'Quintana Roo'),
    ('Sinaloa', 'Sinaloa'),
    ('San Luis Potosí', 'San Luis Potosí'),
    ('Sonora', 'Sonora'),
    ('Tabasco', 'Tabasco'),
    ('Tamaulipas', 'Tamaulipas'),
    ('Tlaxcala', 'Tlaxcala'),
    ('Veracruz', 'Veracruz'),
    ('Yucatán', 'Yucatán'),
    ('Zacatecas', 'Zacatecas')
)
# endregion

# region Upload media folders.
UPLOAD_TO_IMAGES = 'images'
UPLOAD_TO_CATEGORY_ICONS = 'category_icons'
UPLOAD_TO_BANNERS = 'banners'
UPLOAD_TO_MOBILE_BANNERS = 'mobiles_banners'
# endregion

# Validators
PHONE_ERROR = 'Introduzca un número de teléfono valido'
phone_v = validators.RegexValidator(regex=r'^[0-9 -]*$', message=PHONE_ERROR)
NAME_ERROR = 'Este campo solo puede contener letras'
name_v = validators.RegexValidator(
    regex=r'^[a-zA-Z\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff ]*$',
    message=NAME_ERROR)


class BaseModel(models.Model):
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=BASE_MODEL_CREATED
    )
    modified = models.DateTimeField(
        auto_now=True,
        editable=False,
        verbose_name=BASE_MODEL_MODIFIED
    )

    class Meta:
        abstract = True


# Create your models here.
@python_2_unicode_compatible
class Advertiser(BaseModel):
    name = models.CharField(
        max_length=200,
        verbose_name=NAME,
        validators=[name_v]
    )
    last_name = models.CharField(
        max_length=200,
        verbose_name=LAST_NAME,
        validators=[name_v]
    )
    phone = models.CharField(
        max_length=50,
        blank=True,
        verbose_name=PHONE,
        validators=[phone_v]
    )
    cell = models.CharField(
        max_length=50,
        blank=True,
        verbose_name=CELL,
        validators=[phone_v]
    )
    email = models.EmailField(
        blank=True,
        verbose_name=EMAIL
    )
    created_by = models.ForeignKey(
        User,
        related_name='advertiser_created_by',
        verbose_name=BASE_MODE_CREATED_BY
    )
    modified_by = models.ForeignKey(
        User,
        related_name='advertiser_modifies_by',
        verbose_name=BASE_MODE_MODIFIE_BY
    )

    class Meta:
        verbose_name = ADVERTISER
        verbose_name_plural = ADVERTISERS

    def __str__(self):
        return '{0} {1}'.format(self.name, self.last_name)


@python_2_unicode_compatible
class Category(BaseModel):
    name = models.CharField(
        max_length=200,
        verbose_name=CATEGORY_NAME
    )
    icon = models.ImageField(
        upload_to=UPLOAD_TO_CATEGORY_ICONS,
        verbose_name=CATEGORY_ICON
    )
    created_by = models.ForeignKey(
        User,
        related_name='category_created_by',
        verbose_name=BASE_MODE_CREATED_BY
    )
    modified_by = models.ForeignKey(
        User,
        related_name='category_modifies_by',
        verbose_name=BASE_MODE_MODIFIE_BY
    )

    class Meta:
        verbose_name = CATEGORY
        verbose_name_plural = CATEGORIES
        ordering = ['name']

    def __str__(self):
        return '{0}'.format(self.name)


@receiver(models.signals.post_delete, sender=Category)
def auto_delete_category_on_delete(sender, instance, **kwargs):
    if instance.icon:
        if os.path.isfile(instance.icon.path):
            os.remove(instance.icon.path)


@receiver(models.signals.pre_save, sender=Category)
def auto_delete_category_on_change(sender, instance, **kwargs):
    if not instance.pk:
        return False
    try:
        old_file = Category.objects.get(pk=instance.pk).icon
    except Category.DoesNotExist:
        return False

    new_file = instance.icon
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


@python_2_unicode_compatible
class SubCategory(BaseModel):
    name = models.CharField(
        max_length=200,
        verbose_name=SUBCATEGORY_NAME
    )
    category = models.ForeignKey(
        Category,
        verbose_name=CATEGORY
    )
    created_by = models.ForeignKey(
        User,
        related_name='subcategory_created_by',
        verbose_name=BASE_MODE_CREATED_BY
    )
    modified_by = models.ForeignKey(
        User,
        related_name='subcategory_modifies_by',
        verbose_name=BASE_MODE_MODIFIE_BY
    )

    class Meta:
        verbose_name = SUBCATEGORY
        verbose_name_plural = SUBCATEGORIES
        ordering = ['name']

    def __str__(self):
        return '{0}'.format(self.name)


@python_2_unicode_compatible
class Ad(BaseModel):
    title = models.CharField(max_length=200, verbose_name=TITLE)
    trade_name = models.CharField(max_length=200, verbose_name=TRADE_NAME)
    description = models.TextField(blank=True, verbose_name=DESC)
    state = models.CharField(
        max_length=200,
        choices=STATES,
        verbose_name=AD_STATE
    )
    phone = models.CharField(
        max_length=30,
        verbose_name=PHONE,
        validators=[phone_v]
    )
    cell = models.CharField(
        max_length=30,
        blank=True,
        verbose_name=CELL,
        validators=[phone_v]
    )
    date = models.DateTimeField(auto_now_add=True)
    advertiser = models.ForeignKey(Advertiser, verbose_name=ADVERTISER)
    category = models.ForeignKey(Category, verbose_name=CATEGORY_NAME)
    video = models.TextField(max_length=300, blank=True, null=True)
    location = GeopositionField(verbose_name=AD_LOCATION)
    created_by = models.ForeignKey(
        User,
        related_name='ad_created_by',
        verbose_name=BASE_MODE_CREATED_BY
    )
    modified_by = models.ForeignKey(
        User,
        related_name='ad_modifies_by',
        verbose_name=BASE_MODE_MODIFIE_BY
    )

    class Meta:
        verbose_name = AD
        verbose_name_plural = ADS
        ordering = ['title', 'trade_name']

    def __str__(self):
        return self.title


class AdPicture(BaseModel):
    image = models.ImageField(upload_to=UPLOAD_TO_IMAGES)
    ad = models.ForeignKey(Ad, verbose_name=AD)
    created_by = models.ForeignKey(
        User,
        related_name='adpicture_created_by',
        verbose_name=BASE_MODE_CREATED_BY
    )
    modified_by = models.ForeignKey(
        User,
        related_name='adpicture_modifies_by',
        verbose_name=BASE_MODE_MODIFIE_BY
    )

    class Meta:
        verbose_name = IMAGE
        verbose_name_plural = IMAGES

    def __str__(self):
        return '{0}'.format(self.ad.title)


@receiver(models.signals.post_delete, sender=AdPicture)
def auto_delete_ad_picture_on_delete(sender, instance, **kwargs):
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=AdPicture)
def auto_delete_ad_picture_on_change(sender, instance, **kwargs):
    if not instance.pk:
        return False
    try:
        old_file = AdPicture.objects.get(pk=instance.pk).image
    except AdPicture.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


@python_2_unicode_compatible
class Contact(BaseModel):
    address = models.CharField(
        max_length=200,
        verbose_name=CONTACT_ADDRESS
    )
    phone = models.CharField(
        max_length=50,
        verbose_name=CONTACT_PHONE,
        validators=[phone_v]
    )

ads/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    - ¿Quiénes somos?
{% endblock %}
{% block body %}
    <br/>
    <div class="page-header" style="background: url({% static 'img/banner1.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="page-title">¿Quiénes somos?</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main-container">
        <div class="container">
            <p class="info">{{ about_us.about }}</p>
            <br/>
            <div class="row">
                <div class="col-md-4">
                    <h1 class="title-2">Misión</h1>
                    <p class="info">
                        {{ about_us.mission }}
                    </p>
                </div>
                <div class="col-md-4">
                    <h1 class="title-2">Visión</h1>
                    <p class="info">
                        {{ about_us.vision }}
                    </p>
                </div>
                <div class="col-md-4">
                    <h1 class="title-2">Valores</h1>
                    <p class="info">{{ about_us.values }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ads/templates/ad_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    - {{ ad.title }}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/templates/ad_detail.css' %}">
{% endblock %}

{% block body %}
    <div class="main-container">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    {#                #}
                    {% if ad.adpicture_set.all %}
                        <div id="addDetailCarousel" class="carousel slide" data-ride="carousel" data-interval="1000">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                {% for image in ad.adpicture_set.all %}
                                    {% if forloop.first %}
                                        <li data-target="#addDetailCarousel" data-slide-to="{{ forloop.counter }}" class="active"></li>
                                    {% else %}
                                        <li data-target="#addDetailCarousel" data-slide-to="{{ forloop.counter }}"></li>
                                    {% endif %}
                                {% endfor %}
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                                {% for image in ad.adpicture_set.all %}
                                    {% if forloop.first %}
                                        <div class="item active">
                                            <img src="{{ image.image.url }}" width="100%">
                                        </div>
                                    {% else %}
                                        <div class="item">
                                            <img src="{{ image.image.url }}" width="100%">
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <!-- Left and right controls -->
                            <a class="left carousel-control" href="#addDetailCarousel" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#addDetailCarousel" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    {% else %}
                        <img src="{% static 'img/noimage.png' %}" width="100%">
                    {% endif %}
                    {#                #}

                </div>
                <div class="col-md-8">
                    <h2 class="title-2">{{ ad.title }}</h2>
                    <div class="">
                        <p class="info">{{ ad.description }}</p>
                    </div>
                    <div class="contact">
                        <h3 class="title-2">Contacto</h3>
                        <p class="">Nombre: <strong class="text-info">{{ ad.advertiser }}</strong></p>
                        <p>Telefono: <strong class="text-info">{{ ad.phone }}</strong></p>
                        <p>Celular: <strong class="text-info">{{ ad.cell }}</strong></p>
                        <p>Nombre: <strong class="text-info">{{ ad.advertiser.email }}</strong></p>
                    </div>
                    {% if ad.video %}
                        <div>
                            <h3 class="title-2">Video</h3>
                            {% autoescape off %}
                                {{ ad.video }}
                            {% endautoescape %}
                        </div>
                    {% endif %}
                    {% if ad.location %}
                        <div class="contact">
                            <h3 class="title-2">Ubicación</h3>

                            <div class="geoposition-map">
                                <iframe width="100%" height="450" frameborder="0" style="border:0"
                                        src="https://www.google.com/maps/embed/v1/place?q={{ ad.location.latitude }},{{ ad.location.longitude }}&key=AIzaSyBV0WQKgHvutCjB66paz2Y_hxtyBXvz1dw"
                                        allowfullscreen></iframe>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'assets/js/templates/ad_detail.js' %}"></script>
{% endblock %}

ads/templates/ads.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block body %}
    {% if search %}
        <br>
        <div class="container">
            <h1 class="title">
                <strong>{{ ads | length }}</strong> resultado{{ ads|length|pluralize }} para: "<strong>{{ keyword }}</strong>"
            </h1>
        </div>
    {% endif %}
    <div class="container col-md-12">
        {% if ads %}
            <br/>
            {% for ad in ads %}
                <a href="{% url 'ad_detail' pk=ad.pk %}">
                    <div class="box">
                        <div class="row">
                            <div class="">
                                <div class="col-md-3">
                                    {% if ad.adpicture_set.all %}
                                        <img src="{{ ad.adpicture_set.first.image.url }}">
                                    {% else %}
                                        <img src="{% static  'img/noimage.png'%}">
                                    {% endif %}
                                </div>
                                <div>
                                    <span class="title-2">{{ ad.title }}</span>
                                </div>
                                <br/>
                                <div>
                                    <span class="datail">Por {{ ad.advertiser }}</span>
                                </div>
                                <div>
                                    <span class="info">{{ ad.state }}</span>
                                </div>

                            </div>
                        </div>
                    </div>
                </a>
                <br/>
            {% endfor %}

        {% else %}
            <br/>
            <div class="main-text">
                <h2 class="title">NO SE ENCONTRARON RESULTADOS</h2>
            </div>
        {% endif %}
    </div>

{% endblock %}


{% block scripts %}

{% endblock %}

ads/templates/ads_by_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% endblock %}

{% block body %}
    <div class="main-container">
        <div class="container">
            <h1 class="title">{{ category_name }}</h1>
        </div>
        <br/>
        {% if list_ads %}
            <div class="container col-md-8">
                {% for ad in list_ads %}
                    <a href="{% url 'ad_detail' pk=ad.pk %}">
                        <div class="box">
                            <div class="row">
                                <div class="">
                                    <div class="col-md-3">
                                        {% if ad.adpicture_set.all %}
                                            <img src="{{ ad.adpicture_set.first.image.url }}">
                                        {% else %}
                                            <img src="{% static  'img/noimage.png'%}">
                                        {% endif %}
                                    </div>
                                    <div>
                                        <span class="title-2">{{ ad.title }}</span>
                                    </div>
                                    <div>
                                        <span class="datail">Por {{ ad.advertiser }}</span>
                                    </div>
                                    <div>
                                        <span class="info">{{ ad.state }}</span>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </a>
                    <br/>
                {% endfor %}
                {% if is_paginated %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li>
                                <span><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></span>
                            </li>
                        {% endif %}
                        <li class="">
                            <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                        </li>
                        {% if page_obj.has_next %}
                            <li>
                                <span><a href="?page={{ page_obj.next_page_number }}">Siguiente</a></span>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        {% else %}
            <h2 class="title-2">No hay anuncios en esta categoría</h2>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

ads/templates/coupons.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    - Cupones
{% endblock %}

{% block body %}
    <div class="section">
        <div class="container">
            <div class="row">
                <h1 class="title">¡Descarga e imprime tus cupones!</h1>
                <br/>
                {% if coupon %}
                    <div class="container col-md-10">
                        <h2 class="title-2">{{ coupon.name }}</h2>
                        <img src="{{ coupon.coupon.url }}">
                    </div>
                {% else %}
                    <h2 class="title-2">No hay cupones disponibles</h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

ads/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    - Inicio
{% endblock %}

{% block body %}
    <section class="section-title">
        {% if banner_group %}
            <div id="myCarousel" class="carousel slide center" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    {% for banners in banner_group.banner_set.all %}
                        {% if forloop.first %}
                            <li data-target="#myCarousel" data-slide-to="{{ forloop.counter }}" class="active"></li>
                        {% else %}
                            <li data-target="#myCarousel" data-slide-to="{{ forloop.counter }}"></li>
                        {% endif %}
                    {% endfor %}
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    {% for banner in banner_group.banner_set.all %}
                        {% if forloop.first %}
                            <div class="item active carousel-inner" duration="{{ banner.duration }}">
                                <img src="{{ banner.banner.url }}" width="40%">
                            </div>
                        {% else %}
                            <div class="item" duration="{{ banner.duration }}">
                                <img src="{{ banner.banner.url }}" width="40%">
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        {% endif %}

    </section>
    <section id="intro" class="section-intro">
        {% if search %}
            <h1>Resultados</h1>
        {% endif %}
        {#  START OF SEARCH BAR  #}
        <div class="">
            <div class="">
                <div class="main-text">
                    <div class="row search-bar">
                        <div class="advanced-search">
                            <form class="search-form" method="get" action="{% url 'search' %}">
                                {% csrf_token %}
                                {# SELECT FOR CATEGORIES #}
                                <div id="div1" class="col-md-3 col-sm-6 search-col">
                                    <div class="input-group-addon search-category-container">
                                        <label class="styled-select">
                                            <div class="selection_categories">
                                                <select
                                                        id="categories_select"
                                                        name="category"
                                                        class="btn btn-select dropdown-toggle bootstrap-select"
                                                >
                                                    <option value="" selected>Selecciona una categoría</option>
                                                </select>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                                {# SELECT FOR LOCATIONS #}
                                <div id="div2" class="col-md-3 col-sm-6 search-col space-select">
                                    <div class="input-group-addon search-category-container">
                                        <label class="styled-select location-select">
                                            <div class="">
                                                <select
                                                        id="states_select"
                                                        name="state"
                                                        class="btn btn-select dropdown-toggle bootstrap-select"
                                                >
                                                    <option value="" selected>Selecciona una ubicación</option>

                                                </select>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                                {# SEARCH BOX TEXT #}
                                <div  class="col-md-3 col-sm-6 search-col">
                                    <div class="form-group is-empty space-select">
                                        <input
                                                id="keyword"
                                                class="form-control keyword"
                                                name="keyword"
                                                value=""
                                                placeholder="Palabra clave"
                                                type="text"
                                                required
                                        >
                                        <span class="material-input"></span>
                                    </div>
                                    <i class="fa fa-search"></i>
                                </div>
                                {# SEARCH BUTTON #}
                                <div id="boton_centro" class="col-md-3 col-sm-6 search-col">
                                    <input
                                            type="submit"
                                            id="search_button"
                                            class="btn btn-common btn-search btn-block"
                                            value="Buscar"
                                    >
                                    </input>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {#  END OF SEARCH BAR  #}
    </section>
    <section>
        <div class="container">
            <div class="row">
                <h1 class="title-2 section-title">Anuncios recientes</h1>
                {% for recent_ad in recent_ads %}
                    <a href="{% url 'ad_detail' pk=recent_ad.pk %}">
                        <div class="box col-md-4 col-sm-2 recent_ad">
                            <span class="detail">{{ recent_ad.title }}</span>
                            <div class="recent_ad_img">
                                {% if recent_ad.adpicture_set.all %}
                                    <img src="{{ recent_ad.adpicture_set.first.image.url }}">
                                {% else %}
                                    <img src="{% static  'img/noimage.png'%}">
                                {% endif %}
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <h1 class="title-2 section-title">Explora todas las categorías</h1>
            <div class="row">
                {% for category in categories %}
                    <div class="col-md-3 col-sm-6 col-sm-12" style="margin-bottom: 5% ">
                        <div class="container">
                            <a href="{% url 'ads_by_category' pk=category.pk %}">
                                <img class="icon_guide" src="{{ category.icon.url }}">
                                <strong class="category-header">{{ category.name }}</strong>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}
{% endblock %}